sonar.projectKey=T-DAT-902-Homepedia_api
sonar.organization=t-dat-902-homepedia

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**
